# Generated by Django 2.2.14 on 2020-09-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200928_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_decription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
